### ISSUE TITLE
Null pointer stack trace when display model is rendered

### ISSUE THREAD

**Issue by georgweiss** [shroffk/phoebus#1021]
I think a change in @krisztianloki's commit for handling widget errors triggers a stack trace when a display (edit or runtime) is rendered. Root cause is that the widget of type display has no icon. Below is the stack trace. Unfortunately I cannot analyze it in more detail at the moment:
`2019-12-13 09:58:58 WARNING [org.csstudio.display.builder.editor] Cannot obtain widget for display
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at org.csstudio.display.builder.model.WidgetFactory.getWidgetDescriptor(WidgetFactory.java:126)
	at org.csstudio.display.builder.editor.util.WidgetIcons.loadIcon(WidgetIcons.java:43)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.csstudio.display.builder.editor.util.WidgetIcons.getIcon(WidgetIcons.java:36)
	at org.csstudio.display.builder.editor.properties.PropertyPanelSection.bindSimplePropertyField(PropertyPanelSection.java:203)
	at org.csstudio.display.builder.editor.properties.PropertyPanelSection.createPropertyUI(PropertyPanelSection.java:504)
	at org.csstudio.display.builder.editor.properties.PropertyPanelSection.fill(PropertyPanelSection.java:166)
	at org.csstudio.display.builder.editor.properties.PropertyPanel.updatePropertiesView(PropertyPanel.java:141)
	at org.csstudio.display.builder.editor.properties.PropertyPanel.setSelectedWidgets(PropertyPanel.java:90)
	at org.csstudio.display.builder.editor.WidgetSelectionHandler.setSelection(WidgetSelectionHandler.java:67)
	at org.csstudio.display.builder.editor.WidgetSelectionHandler.clear(WidgetSelectionHandler.java:54)
	at org.csstudio.display.builder.editor.DisplayEditor.lambda$setModel$6(DisplayEditor.java:571)
	at org.csstudio.display.builder.representation.javafx.JFXRepresentation.execute(JFXRepresentation.java:669)
	at org.csstudio.display.builder.editor.DisplayEditor.setModel(DisplayEditor.java:571)
	at org.csstudio.display.builder.editor.EditorGUI.lambda$setModel$10(EditorGUI.java:525)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)`

**Comment by kasemir** [comment]
I'll fix it
