### ISSUE TITLE
Example installation fails on windows

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#421]
Error message related to issue parsing "/c:/..." because windows file path is not properly handled.

**Comment by kasemir** [comment]
```
2018-11-12 17:09:38 WARNING [org.phoebus.framework.jobs] Job 'Install Example Displays' failed
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/ky9/Downloads/product-sns-win/product-sns-0.0.1/lib/app-display-model-0.0.1.jar
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.csstudio.display.builder.editor.app.InstallExamplesMenuEntry.lambda$call$1(Unknown Source)
```
