### ISSUE TITLE
Alarm annunciator hangs on shutdown when there's no audio

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#544]
When there's no audio support, for example via remote-ssh, the annunciator won't be able to speak.
Fine.
But on shutdown, we then hang:
```
"Thread-7" #47 daemon prio=5 os_prio=0 cpu=14.57ms elapsed=67.50s tid=0x00007f4474bed800 nid=0x2e206 in Object.wait()  [0x00007f4441103000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.1/Native Method)
        - waiting on <0x0000000742d00438> (a com.sun.speech.freetts.FreeTTSSpeakableImpl)
        at java.lang.Object.wait(java.base@11.0.1/Object.java:328)
        at com.sun.speech.freetts.FreeTTSSpeakableImpl.waitCompleted(FreeTTSSpeakableImpl.java:95)
        - waiting to re-lock in wait() <0x0000000742d00438> (a com.sun.speech.freetts.FreeTTSSpeakableImpl)
        at com.sun.speech.freetts.Voice.speak(Voice.java:298)
        at com.sun.speech.freetts.Voice.speak(Voice.java:235)
        at org.phoebus.applications.alarm.ui.annunciator.Annunciator.speak(Annunciator.java:40)
        at org.phoebus.applications.alarm.ui.annunciator.AnnunciatorController.lambda$new$0(AnnunciatorController.java:97)
        - locked <0x0000000741d04c70> (a java.util.PriorityQueue)
        at org.phoebus.applications.alarm.ui.annunciator.AnnunciatorController$$Lambda$955/0x000000080061b840.run(Unknown Source)
        at java.lang.Thread.run(java.base@11.0.1/Thread.java:834)

"JavaFX Application Thread" #18 prio=5 os_prio=0 cpu=3366.61ms elapsed=71.07s tid=0x00007f4491172800 nid=0x2e1dd waiting for monitor entry  [0x00007f444d104000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.phoebus.applications.alarm.ui.annunciator.AnnunciatorController.shutdown(AnnunciatorController.java:156)
        - waiting to lock <0x0000000741d04c70> (a java.util.PriorityQueue)
        at org.phoebus.applications.alarm.ui.annunciator.AnnunciatorTable.shutdown(AnnunciatorTable.java:340)
        at org.phoebus.applications.alarm.ui.annunciator.AnnunciatorTableInstance.dispose(AnnunciatorTableInstance.java:118)
        at org.phoebus.applications.alarm.ui.annunciator.AnnunciatorTableInstance.lambda$new$1(AnnunciatorTableInstance.java:48)
        at org.phoebus.applications.alarm.ui.annunciator.AnnunciatorTableInstance$$Lambda$962/0x000000080061a440.getAsBoolean(Unknown Source)
        at org.phoebus.ui.docking.DockItem.lambda$addCloseCheck$10(DockItem.java:504)
        at org.phoebus.ui.docking.DockItem$$Lambda$679/0x00000008004c8c40.handle(Unknown Source)
        at org.phoebus.ui.docking.DockItem.close(DockItem.java:557)
        at org.phoebus.ui.docking.DockStage.isStageOkToClose(DockStage.java:181)
```

**Comment by kasemir** [comment]
Rework of AnnunciatorController replaces synchronized sections with queue in a way that allows app to exit even if speech is hung.
