### ISSUE TITLE
Preference size limit

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#779]
There is some hidden size limit for preferences:

java.lang.IllegalArgumentException: Value too long: cadf:/ade/archiver...
        at java.prefs/java.util.prefs.AbstractPreferences.put(AbstractPreferences.java:253)
        at org.phoebus.framework.preferences.PropertyPreferenceLoader.load(PropertyPreferenceLoader.java:44)
        at org.phoebus.product.Launcher.main(Launcher.java:94)

**Comment by kasemir** [comment]
In JDK12 it's this:
```
    /**
     * Maximum length of string allowed as a value (8192 characters).
     */
    public static final int MAX_VALUE_LENGTH = 8*1024;
```

-> Can't do anything about it.
