### ISSUE TITLE
File Browser can block UI when file system is not responging

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#796]
When opening the file browser to a file system that's slow/blocked, for example because it's NFS mounted and there are problems, the UI can hang like this:
```
"JavaFX Application Thread" #18 prio=5 os_prio=0 cpu=732.16ms elapsed=112.62s tid=0x00007fe18ce71000 nid=0x174f runnable  [0x00007fe14d8d3000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.getBooleanAttributes0(java.base@12.0.1/Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(java.base@12.0.1/UnixFileSystem.java:250)
	at java.io.File.isHidden(java.base@12.0.1/File.java:912)
	at org.phoebus.applications.filebrowser.FileTreeItem.buildChildren(FileTreeItem.java:85)
	at org.phoebus.applications.filebrowser.FileTreeItem.getChildren(FileTreeItem.java:53)
	at javafx.scene.control.TreeItem.updateExpandedDescendentCount(TreeItem.java:915)
...
```

**Comment by kasemir** [comment]
The specific issue caught in stack trace has been fixed by listing files off the UI thread.
There could be more issues, re-open as stack traces become available.
